name: 🚀 Auto Deploy to nexiuslabs.com

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Upload via rsync to server
        uses: burnett01/rsync-deployments@v2
        with:
          switches: -avzr --delete
          path: dist/                                 # or build/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_port: ${{ secrets.SERVER_PORT }}
          remote_path: /var/www/nexiuslabs.com        # must match Nginx root
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl reload nginx
